# wrangler.toml
name = 'vbelle-store'
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
main = "worker.ts" # Worker entrypoint after build

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[workflows]]
name = "my-workflow"
binding = "MY_WORKFLOW"
class_name = "MyWorkflow"